# ======================================================================================
# ALEMBIC MIGRATION TEMPLATE (script.py.mako)
# ======================================================================================
# This is a blueprint/template file used automatically by Alembic.
# Whenever you run 'alembic revision', Alembic copies this file, replaces the  
# placeholders with real data (dates, IDs), and creates a new script in 'versions/'.
# Do NOT modify the syntax of this file unless you want to change the global structure 
# of all future migration files.
# ======================================================================================

"""create telemetry table

Revision ID: c258a9ed31eb
Revises: fd4898694da5
Create Date: 2026-06-08 18:31:38.710122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# Unique ID of this migration.
revision: str = 'c258a9ed31eb'

# Previous migration ID.
# This creates the migration chain/order.
down_revision: Union[str, None] = 'fd4898694da5'

# Advanced Alembic feature for branching migrations.
# Usually not used in this project.
branch_labels: Union[str, Sequence[str], None] = None

# Advanced Alembic feature for migration dependencies.
# Usually not used in this project.
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Forward change: create/update database schema.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telemetry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('speed', sa.Float(), nullable=False),
    sa.Column('battery', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_agent_id'), 'telemetry', ['agent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # Rollback change: undo what upgrade() did.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telemetry_agent_id'), table_name='telemetry')
    op.drop_table('telemetry')
    # ### end Alembic commands ###