"""create alerts table

Revision ID: c5e951e8780d
Revises: c258a9ed31eb
Create Date: 2026-06-18 14:23:24.473091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# Unique ID of this migration.
revision: str = 'c5e951e8780d'

# Previous migration ID.
# This creates the migration chain/order.
down_revision: Union[str, None] = 'c258a9ed31eb'

# Advanced Alembic feature for branching migrations.
# Usually not used in this project.
branch_labels: Union[str, Sequence[str], None] = None

# Advanced Alembic feature for migration dependencies.
# Usually not used in this project.
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Forward change: create/update database schema.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_agent_id'), 'alerts', ['agent_id'], unique=False)
    # Partial unique index: only one active (unresolved) alert per agent+type at a time.
    # resolved_at IS NULL means the alert is still active.
    op.create_index(
        'uix_alerts_active_agent_type',
        'alerts',
        ['agent_id', 'alert_type'],
        unique=True,
        postgresql_where=sa.text('resolved_at IS NULL'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # Rollback change: undo what upgrade() did.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uix_alerts_active_agent_type', table_name='alerts')
    op.drop_index(op.f('ix_alerts_agent_id'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###