# ======================================================================================
# ALEMBIC MIGRATION TEMPLATE (script.py.mako)
# ======================================================================================
# This is a blueprint/template file used automatically by Alembic.
# Whenever you run 'alembic revision', Alembic copies this file, replaces the  
# placeholders with real data (dates, IDs), and creates a new script in 'versions/'.
# Do NOT modify the syntax of this file unless you want to change the global structure 
# of all future migration files.
# ======================================================================================

"""create agents table

Revision ID: fd4898694da5
Revises: 
Create Date: 2026-06-07 20:26:06.814228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# Unique ID of this migration.
revision: str = 'fd4898694da5'

# Previous migration ID.
# This creates the migration chain/order.
down_revision: Union[str, None] = None

# Advanced Alembic feature for branching migrations.
# Usually not used in this project.
branch_labels: Union[str, Sequence[str], None] = None

# Advanced Alembic feature for migration dependencies.
# Usually not used in this project.
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Forward change: create/update database schema.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='offline', nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # Rollback change: undo what upgrade() did.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agents')
    # ### end Alembic commands ###